name: example
publish_to: none

environment:
  sdk: ^3.0.0

dependencies:
  stub_kit:
    path: ../

dev_dependencies:
  build_runner: ^2.0.0
  build_verify: ^3.0.0
  dart_flutter_team_lints: ^2.0.0
  test: ^1.5.1


