name: example
publish_to: none

environment:
  sdk: ^3.0.0

dependencies:
  freezed: any
  freezed_annotation: any
  stub_kit:
    path: ../

dev_dependencies:
  build_runner: ^2.0.0
  build_verify: ^3.0.0
  json_serializable: any
  lint: ^2.0.0
  test: ^1.5.1


