# Read about `build.yaml` at https://pub.dev/packages/build_config
builders:
  stub_gen:
    import: "package:stub_gen/builder.dart"
    builder_factories: ["stubBuilder"]
    build_extensions: { ".dart": [".stub.dart"] }
    auto_apply: dependents
    build_to: source
    applies_builders: ["source_gen|combining_builder"]
