name: stub_kit
description: A new Flutter package project.
version: 0.0.1

environment:
  sdk: '>=3.1.3 <4.0.0'

dependencies:
  analyzer: ^6.2.0
  build: ^2.4.1
  source_gen: ^1.5.0

dev_dependencies:
  lint: ^2.0.0
  test: ^1.5.1
